from django.core.management.base import BaseCommand
from core.models import Listing

class Command(BaseCommand):
    help = "Seed 50 real accessible venues in London"

    def handle(self, *args, **kwargs):
        london_venues = [
            # Museums & Galleries
            {"name": "British Museum", "subtitle": "World-renowned museum with extensive accessibility", "categories": ["Entertainment", "Education"], "address": "Great Russell St, London WC1B 3DG", "lat": 51.5194, "lng": -0.1270, "phone": "+44 20 7323 8299", "website": "https://www.britishmuseum.org", "rating": 4.7, "reviews_count": 95000, "accessibility_features": ["wheelchair", "audio-guides", "accessible-restroom"]},
            {"name": "Natural History Museum", "subtitle": "Iconic museum with step-free access", "categories": ["Entertainment", "Education"], "address": "Cromwell Rd, London SW7 5BD", "lat": 51.4967, "lng": -0.1764, "phone": "+44 20 7942 5000", "website": "https://www.nhm.ac.uk", "rating": 4.7, "reviews_count": 78000, "accessibility_features": ["wheelchair", "accessible-restroom", "lifts"]},
            {"name": "Science Museum", "subtitle": "Interactive science exhibits, fully accessible", "categories": ["Entertainment", "Education"], "address": "Exhibition Rd, London SW7 2DD", "lat": 51.4978, "lng": -0.1746, "phone": "+44 20 7942 4000", "website": "https://www.sciencemuseum.org.uk", "rating": 4.6, "reviews_count": 52000, "accessibility_features": ["wheelchair", "accessible-restroom", "tactile-exhibits"]},
            {"name": "Victoria and Albert Museum", "subtitle": "World's leading museum of art and design", "categories": ["Entertainment", "Education"], "address": "Cromwell Rd, London SW7 2RL", "lat": 51.4966, "lng": -0.1722, "phone": "+44 20 7942 2000", "website": "https://www.vam.ac.uk", "rating": 4.7, "reviews_count": 45000, "accessibility_features": ["wheelchair", "audio-guides", "accessible-restroom"]},
            {"name": "Tate Modern", "subtitle": "Contemporary art gallery with excellent access", "categories": ["Entertainment"], "address": "Bankside, London SE1 9TG", "lat": 51.5076, "lng": -0.0994, "phone": "+44 20 7887 8888", "website": "https://www.tate.org.uk/visit/tate-modern", "rating": 4.6, "reviews_count": 68000, "accessibility_features": ["wheelchair", "lifts", "accessible-restroom"]},
            {"name": "National Gallery", "subtitle": "European paintings with full accessibility", "categories": ["Entertainment", "Education"], "address": "Trafalgar Square, London WC2N 5DN", "lat": 51.5089, "lng": -0.1283, "phone": "+44 20 7747 2885", "website": "https://www.nationalgallery.org.uk", "rating": 4.7, "reviews_count": 42000, "accessibility_features": ["wheelchair", "audio-guides", "accessible-restroom"]},
            {"name": "Imperial War Museum", "subtitle": "War history museum with step-free access", "categories": ["Entertainment", "Education"], "address": "Lambeth Rd, London SE1 6HZ", "lat": 51.4958, "lng": -0.1085, "phone": "+44 20 7416 5000", "website": "https://www.iwm.org.uk", "rating": 4.6, "reviews_count": 28000, "accessibility_features": ["wheelchair", "accessible-restroom", "lifts"]},
            {"name": "Design Museum", "subtitle": "Contemporary design with accessible facilities", "categories": ["Entertainment"], "address": "224-238 Kensington High St, London W8 6AG", "lat": 51.4999, "lng": -0.2026, "phone": "+44 20 3862 5900", "website": "https://designmuseum.org", "rating": 4.5, "reviews_count": 12000, "accessibility_features": ["wheelchair", "accessible-restroom", "lifts"]},
            
            # Restaurants & Cafes
            {"name": "Dishoom Covent Garden", "subtitle": "Accessible Indian restaurant with vibrant atmosphere", "categories": ["Food & Drink"], "address": "12 Upper St Martin's Ln, London WC2H 9FB", "lat": 51.5115, "lng": -0.1268, "phone": "+44 20 7420 9320", "website": "https://www.dishoom.com", "rating": 4.5, "reviews_count": 8500, "price_min": 15, "price_max": 35, "accessibility_features": ["wheelchair", "accessible-restroom"]},
            {"name": "Sketch", "subtitle": "Quirky restaurant with excellent accessibility", "categories": ["Food & Drink"], "address": "9 Conduit St, London W1S 2XG", "lat": 51.5134, "lng": -0.1408, "phone": "+44 20 7659 4500", "website": "https://sketch.london", "rating": 4.3, "reviews_count": 6200, "price_min": 40, "price_max": 120, "accessibility_features": ["wheelchair", "accessible-restroom", "lifts"]},
            {"name": "The Ivy", "subtitle": "Classic British dining with step-free access", "categories": ["Food & Drink"], "address": "1-5 West St, London WC2H 9NQ", "lat": 51.5124, "lng": -0.1281, "phone": "+44 20 7836 4751", "website": "https://www.the-ivy.co.uk", "rating": 4.4, "reviews_count": 5800, "price_min": 30, "price_max": 80, "accessibility_features": ["wheelchair", "accessible-restroom"]},
            {"name": "Flat Iron Square", "subtitle": "Food market with accessible seating", "categories": ["Food & Drink"], "address": "68 Union St, London SE1 1TD", "lat": 51.5043, "lng": -0.0932, "phone": "+44 20 3019 7350", "website": "https://flatironsquare.co.uk", "rating": 4.2, "reviews_count": 3400, "price_min": 10, "price_max": 25, "accessibility_features": ["wheelchair", "wide-aisles"]},
            {"name": "Borough Market", "subtitle": "Historic food market with level access", "categories": ["Food & Drink"], "address": "8 Southwark St, London SE1 1TL", "lat": 51.5055, "lng": -0.0909, "phone": "+44 20 7407 1002", "website": "https://boroughmarket.org.uk", "rating": 4.5, "reviews_count": 28000, "price_min": 5, "price_max": 30, "accessibility_features": ["wheelchair", "wide-aisles"]},
            {"name": "Ottolenghi Islington", "subtitle": "Mediterranean cafe with accessible entrance", "categories": ["Food & Drink"], "address": "287 Upper St, London N1 2TZ", "lat": 51.5445, "lng": -0.1032, "phone": "+44 20 7288 1454", "website": "https://ottolenghi.co.uk", "rating": 4.4, "reviews_count": 2100, "price_min": 12, "price_max": 30, "accessibility_features": ["wheelchair", "accessible-restroom"]},
            {"name": "Monmouth Coffee", "subtitle": "Specialty coffee with step-free access", "categories": ["Food & Drink"], "address": "27 Monmouth St, London WC2H 9EU", "lat": 51.5141, "lng": -0.1260, "phone": "+44 20 7232 3010", "website": "https://monmouthcoffee.co.uk", "rating": 4.5, "reviews_count": 3200, "price_min": 3, "price_max": 8, "accessibility_features": ["wheelchair", "wide-aisles"]},
            
            # Hotels
            {"name": "The Savoy", "subtitle": "Luxury hotel with full accessibility features", "categories": ["Accommodation"], "address": "Strand, London WC2R 0EZ", "lat": 51.5104, "lng": -0.1206, "phone": "+44 20 7836 4343", "website": "https://www.thesavoylondon.com", "rating": 4.6, "reviews_count": 8500, "price_min": 400, "price_max": 1200, "accessibility_features": ["wheelchair", "accessible-restroom", "lifts", "accessible-rooms"]},
            {"name": "Hilton London Bankside", "subtitle": "Modern hotel with accessible rooms", "categories": ["Accommodation"], "address": "2-8 Great Suffolk St, London SE1 0UG", "lat": 51.5037, "lng": -0.0979, "phone": "+44 20 3503 3888", "website": "https://www.hilton.com", "rating": 4.3, "reviews_count": 4200, "price_min": 150, "price_max": 350, "accessibility_features": ["wheelchair", "accessible-restroom", "lifts", "accessible-rooms"]},
            {"name": "Premier Inn London County Hall", "subtitle": "Accessible budget hotel near attractions", "categories": ["Accommodation"], "address": "Belvedere Rd, London SE1 7PB", "lat": 51.5015, "lng": -0.1173, "phone": "+44 871 527 8648", "website": "https://www.premierinn.com", "rating": 4.2, "reviews_count": 6800, "price_min": 80, "price_max": 180, "accessibility_features": ["wheelchair", "accessible-restroom", "lifts", "accessible-rooms"]},
            {"name": "Citizen M Tower of London", "subtitle": "Contemporary hotel with accessibility", "categories": ["Accommodation"], "address": "40 Trinity Square, London EC3N 4DJ", "lat": 51.5095, "lng": -0.0754, "phone": "+44 20 3519 4830", "website": "https://www.citizenm.com", "rating": 4.4, "reviews_count": 3900, "price_min": 120, "price_max": 280, "accessibility_features": ["wheelchair", "accessible-restroom", "lifts"]},
            
            # Attractions & Entertainment
            {"name": "London Eye", "subtitle": "Iconic observation wheel with accessible capsules", "categories": ["Entertainment"], "address": "Riverside Building, County Hall, London SE1 7PB", "lat": 51.5033, "lng": -0.1195, "phone": "+44 871 781 3000", "website": "https://www.londoneye.com", "rating": 4.5, "reviews_count": 125000, "price_min": 27, "price_max": 45, "accessibility_features": ["wheelchair", "accessible-restroom", "priority-boarding"]},
            {"name": "Tower of London", "subtitle": "Historic castle with accessible routes", "categories": ["Entertainment", "Education"], "address": "London EC3N 4AB", "lat": 51.5081, "lng": -0.0759, "phone": "+44 20 3166 6000", "website": "https://www.hrp.org.uk/tower-of-london", "rating": 4.6, "reviews_count": 98000, "price_min": 29, "price_max": 34, "accessibility_features": ["wheelchair", "accessible-restroom", "audio-guides"]},
            {"name": "Westminster Abbey", "subtitle": "Gothic church with accessible entrance", "categories": ["Entertainment", "Education"], "address": "20 Deans Yd, London SW1P 3PA", "lat": 51.4993, "lng": -0.1273, "phone": "+44 20 7222 5152", "website": "https://www.westminster-abbey.org", "rating": 4.6, "reviews_count": 42000, "price_min": 24, "price_max": 27, "accessibility_features": ["wheelchair", "accessible-restroom", "audio-guides"]},
            {"name": "St Paul's Cathedral", "subtitle": "Iconic cathedral with step-free access to main floor", "categories": ["Entertainment", "Education"], "address": "St. Paul's Churchyard, London EC4M 8AD", "lat": 51.5138, "lng": -0.0984, "phone": "+44 20 7246 8350", "website": "https://www.stpauls.co.uk", "rating": 4.7, "reviews_count": 38000, "price_min": 20, "price_max": 23, "accessibility_features": ["wheelchair", "accessible-restroom", "audio-guides"]},
            {"name": "Shakespeare's Globe", "subtitle": "Theatre with accessible seating and facilities", "categories": ["Entertainment"], "address": "21 New Globe Walk, London SE1 9DT", "lat": 51.5081, "lng": -0.0972, "phone": "+44 20 7401 9919", "website": "https://www.shakespearesglobe.com", "rating": 4.6, "reviews_count": 12000, "price_min": 17, "price_max": 62, "accessibility_features": ["wheelchair", "accessible-restroom", "accessible-seating"]},
            {"name": "Royal Opera House", "subtitle": "World-class opera with excellent accessibility", "categories": ["Entertainment"], "address": "Bow St, London WC2E 9DD", "lat": 51.5129, "lng": -0.1220, "phone": "+44 20 7304 4000", "website": "https://www.roh.org.uk", "rating": 4.6, "reviews_count": 8500, "price_min": 25, "price_max": 250, "accessibility_features": ["wheelchair", "accessible-restroom", "accessible-seating", "hearing-loop"]},
            {"name": "Kew Gardens", "subtitle": "Botanical gardens with accessible paths", "categories": ["Entertainment"], "address": "Richmond, London TW9 3AE", "lat": 51.4779, "lng": -0.2947, "phone": "+44 20 8332 5655", "website": "https://www.kew.org", "rating": 4.7, "reviews_count": 32000, "price_min": 18, "price_max": 22, "accessibility_features": ["wheelchair", "accessible-restroom", "mobility-scooters"]},
            {"name": "ZSL London Zoo", "subtitle": "Historic zoo with accessible pathways", "categories": ["Entertainment"], "address": "Regent's Park, London NW1 4RY", "lat": 51.5352, "lng": -0.1534, "phone": "+44 344 225 1826", "website": "https://www.zsl.org/zsl-london-zoo", "rating": 4.4, "reviews_count": 28000, "price_min": 27, "price_max": 35, "accessibility_features": ["wheelchair", "accessible-restroom", "mobility-scooters"]},
            {"name": "SEA LIFE London Aquarium", "subtitle": "Aquarium with step-free access throughout", "categories": ["Entertainment"], "address": "County Hall, Westminster Bridge Rd, London SE1 7PB", "lat": 51.5017, "lng": -0.1188, "phone": "+44 871 663 1678", "website": "https://www.visitsealife.com/london", "rating": 4.3, "reviews_count": 18000, "price_min": 28, "price_max": 35, "accessibility_features": ["wheelchair", "accessible-restroom", "lifts"]},
            {"name": "Madame Tussauds", "subtitle": "Wax museum with accessible facilities", "categories": ["Entertainment"], "address": "Marylebone Rd, London NW1 5LR", "lat": 51.5229, "lng": -0.1547, "phone": "+44 871 894 3000", "website": "https://www.madametussauds.com/london", "rating": 4.2, "reviews_count": 42000, "price_min": 33, "price_max": 45, "accessibility_features": ["wheelchair", "accessible-restroom", "lifts"]},
            
            # Parks & Recreation
            {"name": "Hyde Park", "subtitle": "Royal park with accessible paths and facilities", "categories": ["Entertainment"], "address": "London W2 2UH", "lat": 51.5074, "lng": -0.1657, "phone": "+44 300 061 2000", "website": "https://www.royalparks.org.uk/parks/hyde-park", "rating": 4.7, "reviews_count": 85000, "accessibility_features": ["wheelchair", "accessible-restroom", "paved-paths"]},
            {"name": "Regent's Park", "subtitle": "Beautiful park with step-free access", "categories": ["Entertainment"], "address": "Chester Rd, London NW1 4NR", "lat": 51.5313, "lng": -0.1563, "phone": "+44 300 061 2300", "website": "https://www.royalparks.org.uk/parks/the-regents-park", "rating": 4.7, "reviews_count": 32000, "accessibility_features": ["wheelchair", "accessible-restroom", "paved-paths"]},
            {"name": "Greenwich Park", "subtitle": "Historic park with accessible routes", "categories": ["Entertainment"], "address": "London SE10 8QY", "lat": 51.4769, "lng": -0.0005, "phone": "+44 300 061 2380", "website": "https://www.royalparks.org.uk/parks/greenwich-park", "rating": 4.7, "reviews_count": 28000, "accessibility_features": ["wheelchair", "accessible-restroom", "paved-paths"]},
            
            # Shopping
            {"name": "Harrods", "subtitle": "Luxury department store with full accessibility", "categories": ["Entertainment"], "address": "87-135 Brompton Rd, London SW1X 7XL", "lat": 51.4994, "lng": -0.1634, "phone": "+44 20 7730 1234", "website": "https://www.harrods.com", "rating": 4.5, "reviews_count": 68000, "accessibility_features": ["wheelchair", "accessible-restroom", "lifts", "mobility-scooters"]},
            {"name": "Covent Garden Market", "subtitle": "Shopping area with level access", "categories": ["Entertainment"], "address": "The Market, Covent Garden, London WC2E 8RF", "lat": 51.5118, "lng": -0.1226, "phone": "+44 20 7420 5856", "website": "https://www.coventgarden.london", "rating": 4.5, "reviews_count": 42000, "accessibility_features": ["wheelchair", "accessible-restroom", "lifts"]},
            {"name": "Westfield London", "subtitle": "Shopping centre with excellent accessibility", "categories": ["Entertainment"], "address": "Ariel Way, London W12 7GF", "lat": 51.5074, "lng": -0.2208, "phone": "+44 20 3371 2300", "website": "https://uk.westfield.com/london", "rating": 4.4, "reviews_count": 52000, "accessibility_features": ["wheelchair", "accessible-restroom", "lifts", "mobility-scooters"]},
            
            # Libraries & Education
            {"name": "British Library", "subtitle": "National library with full accessibility", "categories": ["Education"], "address": "96 Euston Rd, London NW1 2DB", "lat": 51.5298, "lng": -0.1270, "phone": "+44 33 0333 1144", "website": "https://www.bl.uk", "rating": 4.6, "reviews_count": 12000, "accessibility_features": ["wheelchair", "accessible-restroom", "lifts", "hearing-loop"]},
            {"name": "Wellcome Collection", "subtitle": "Free museum with accessible facilities", "categories": ["Entertainment", "Education"], "address": "183 Euston Rd, London NW1 2BE", "lat": 51.5259, "lng": -0.1338, "phone": "+44 20 7611 2222", "website": "https://wellcomecollection.org", "rating": 4.6, "reviews_count": 8200, "accessibility_features": ["wheelchair", "accessible-restroom", "lifts"]},
            
            # Sports & Leisure
            {"name": "Wembley Stadium", "subtitle": "National stadium with accessible seating", "categories": ["Sport"], "address": "Wembley, London HA9 0WS", "lat": 51.5560, "lng": -0.2795, "phone": "+44 800 169 9933", "website": "https://www.wembleystadium.com", "rating": 4.6, "reviews_count": 42000, "price_min": 30, "price_max": 150, "accessibility_features": ["wheelchair", "accessible-restroom", "accessible-seating", "lifts"]},
            {"name": "The O2 Arena", "subtitle": "Entertainment venue with excellent accessibility", "categories": ["Entertainment", "Sport"], "address": "Peninsula Square, London SE10 0DX", "lat": 51.5031, "lng": 0.0030, "phone": "+44 20 8463 2000", "website": "https://www.theo2.co.uk", "rating": 4.5, "reviews_count": 38000, "price_min": 25, "price_max": 200, "accessibility_features": ["wheelchair", "accessible-restroom", "accessible-seating", "lifts"]},
            {"name": "Emirates Stadium", "subtitle": "Arsenal FC stadium with accessible facilities", "categories": ["Sport"], "address": "Hornsey Rd, London N7 7AJ", "lat": 51.5549, "lng": -0.1084, "phone": "+44 20 7619 5003", "website": "https://www.arsenal.com", "rating": 4.6, "reviews_count": 28000, "price_min": 35, "price_max": 120, "accessibility_features": ["wheelchair", "accessible-restroom", "accessible-seating", "lifts"]},
            
            # Theatres
            {"name": "National Theatre", "subtitle": "World-class theatre with full accessibility", "categories": ["Entertainment"], "address": "South Bank, London SE1 9PX", "lat": 51.5076, "lng": -0.1145, "phone": "+44 20 7452 3000", "website": "https://www.nationaltheatre.org.uk", "rating": 4.6, "reviews_count": 12000, "price_min": 15, "price_max": 75, "accessibility_features": ["wheelchair", "accessible-restroom", "accessible-seating", "hearing-loop"]},
            {"name": "Barbican Centre", "subtitle": "Arts centre with excellent accessibility", "categories": ["Entertainment"], "address": "Silk St, London EC2Y 8DS", "lat": 51.5200, "lng": -0.0936, "phone": "+44 20 7638 8891", "website": "https://www.barbican.org.uk", "rating": 4.5, "reviews_count": 8500, "price_min": 12, "price_max": 85, "accessibility_features": ["wheelchair", "accessible-restroom", "accessible-seating", "hearing-loop", "lifts"]},
            {"name": "Royal Albert Hall", "subtitle": "Historic venue with accessible seating", "categories": ["Entertainment"], "address": "Kensington Gore, London SW7 2AP", "lat": 51.5009, "lng": -0.1773, "phone": "+44 20 7589 8212", "website": "https://www.royalalberthall.com", "rating": 4.7, "reviews_count": 22000, "price_min": 20, "price_max": 150, "accessibility_features": ["wheelchair", "accessible-restroom", "accessible-seating", "hearing-loop"]},
            
            # Additional Venues
            {"name": "Churchill War Rooms", "subtitle": "Historic bunker with accessible lift", "categories": ["Entertainment", "Education"], "address": "Clive Steps, King Charles St, London SW1A 2AQ", "lat": 51.5022, "lng": -0.1291, "phone": "+44 20 7416 5000", "website": "https://www.iwm.org.uk/visits/churchill-war-rooms", "rating": 4.7, "reviews_count": 18000, "price_min": 25, "price_max": 28, "accessibility_features": ["wheelchair", "accessible-restroom", "lifts"]},
            {"name": "HMS Belfast", "subtitle": "Historic warship with accessible areas", "categories": ["Entertainment", "Education"], "address": "The Queen's Walk, London SE1 2JH", "lat": 51.5065, "lng": -0.0814, "phone": "+44 20 7940 6300", "website": "https://www.iwm.org.uk/visits/hms-belfast", "rating": 4.5, "reviews_count": 15000, "price_min": 22, "price_max": 25, "accessibility_features": ["wheelchair", "accessible-restroom"]},
            {"name": "Sky Garden", "subtitle": "Free viewing platform with accessible lift", "categories": ["Entertainment"], "address": "1 Sky Garden Walk, London EC3M 8AF", "lat": 51.5111, "lng": -0.0834, "phone": "+44 33 0772 0020", "website": "https://skygarden.london", "rating": 4.4, "reviews_count": 28000, "accessibility_features": ["wheelchair", "accessible-restroom", "lifts"]},
            {"name": "The Shard", "subtitle": "Viewing platform with accessible facilities", "categories": ["Entertainment"], "address": "32 London Bridge St, London SE1 9SG", "lat": 51.5045, "lng": -0.0865, "phone": "+44 844 499 7111", "website": "https://www.theviewfromtheshard.com", "rating": 4.5, "reviews_count": 42000, "price_min": 28, "price_max": 35, "accessibility_features": ["wheelchair", "accessible-restroom", "lifts"]},
            {"name": "Camden Market", "subtitle": "Alternative market with accessible areas", "categories": ["Food & Drink", "Entertainment"], "address": "Camden Lock Pl, London NW1 8AF", "lat": 51.5417, "lng": -0.1463, "phone": "+44 20 7485 7963", "website": "https://www.camdenmarket.com", "rating": 4.4, "reviews_count": 38000, "accessibility_features": ["wheelchair", "wide-aisles"]},
            {"name": "Southbank Centre", "subtitle": "Cultural complex with full accessibility", "categories": ["Entertainment"], "address": "Belvedere Rd, London SE1 8XX", "lat": 51.5056, "lng": -0.1158, "phone": "+44 20 3879 9555", "website": "https://www.southbankcentre.co.uk", "rating": 4.5, "reviews_count": 12000, "accessibility_features": ["wheelchair", "accessible-restroom", "lifts", "hearing-loop"]},
        ]

        created_count = 0
        updated_count = 0
        
        for venue_data in london_venues:
            listing, created = Listing.objects.update_or_create(
                name=venue_data["name"],
                defaults={
                    **venue_data,
                    "city": "London",
                    "country": "UK",
                    "status": "open",
                    "moderation_status": "approved",
                    "featured": venue_data.get("rating", 0) >= 4.6
                }
            )
            
            if created:
                created_count += 1
                self.stdout.write(self.style.SUCCESS(f"✓ Created: {listing.name}"))
            else:
                updated_count += 1
                self.stdout.write(self.style.WARNING(f"○ Updated: {listing.name}"))

        self.stdout.write(self.style.SUCCESS(f"\n✓ Complete! Created {created_count} new venues, updated {updated_count}."))
        self.stdout.write(self.style.SUCCESS(f"Total London venues: {len(london_venues)}"))
