# Generated by Django 6.0 on 2026-01-07 13:28

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_alter_listing_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.listing_photo_path)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(blank=True, help_text='Description for screen readers', max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary photo shown in listings and map')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_photos', to='core.listing')),
            ],
            options={
                'verbose_name': 'Listing Photo',
                'verbose_name_plural': 'Listing Photos',
                'ordering': ['-is_primary', '-uploaded_at'],
            },
        ),
    ]
