# Generated by Django 6.0 on 2026-01-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('sponsor', 'Sponsor'), ('partner', 'Partner & Friend')], default='partner', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/')),
                ('description', models.TextField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['type', 'order', 'name'],
            },
        ),
    ]
