# Generated by Django 6.0 on 2026-01-07 16:50

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_donationgoal_sponsorshippackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='donationgoal',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
